spring.application.name=club-api
server.port=8082

# ===================== CONEXIÓN A MONGODB ATLAS =====================
# Reemplace TODA la cadena por la que le da Atlas en: Connect > Drivers > Java.
#  - Cambie <db_password> por la contraseña del usuario de base de datos.
#  - Después de ".mongodb.net/" escriba el nombre de la base: agenda
# Ejemplo:
# mongodb+srv://estudiante:MiClave123@cluster0.ab1cd.mongodb.net/agenda?retryWrites=true&w=majority&appName=Cluster0
#
# (Opcional) también puede dejar esta línea igual y crear una variable de entorno MONGODB_URI.
spring.data.mongodb.uri=mongodb+srv://agenda:agenda@app.qacuu93.mongodb.net/agenda?retryWrites=true&w=majority&appName=APP
spring.data.mongodb.database=agenda

# Cargar datos de ejemplo (Millonarios, Santa Fe, FCF...) si la base está vacía
app.datos-demo=true

# Mostrar el mensaje de error en las respuestas JSON
server.error.include-message=always
